export const RESET_ERROR_MESSAGE = "RESET_ERROR_MESSAGE";
export const WAIT_FOR_RESULT = "WAIT_FOR_RESULT";
export const DISPLAY_BOARD_CONTENT = "DISPLAY_BOARD_CONTENT";
export const SHOW_ERROR_MESSAGE = "SHOW_ERROR_MESSAGE";
export const ADD_NEW_CARD_IN_COLUMN = "ADD_NEW_CARD_IN_COLUMN";
export const DELETE_CARD_FROM_COLUMN = "DELETE_CARD_FROM_COLUMN";
export const EDIT_CONTENT = "EDIT_CONTENT";